# Generated by Django 4.2.7 on 2023-12-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('score', models.FloatField(default='0')),
                ('price', models.FloatField(default='0')),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
                ('score', models.FloatField(default=0)),
                ('average', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'riders',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('student_id', models.CharField(max_length=128)),
                ('building_id', models.CharField(max_length=128)),
                ('room_id', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'types',
            },
        ),
    ]
