# Generated by Django 4.2.7 on 2023-12-03 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='0')),
                ('order_id', models.IntegerField(default='0')),
                ('content', models.TextField(default='')),
                ('score', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 12, 3, 16, 44, 4, 255177))),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='0')),
                ('price', models.FloatField(default='0')),
            ],
            options={
                'db_table': 'histories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='0')),
                ('rider_id', models.IntegerField(default='0')),
                ('comment_id', models.IntegerField(default='0')),
                ('merchant_id', models.IntegerField(default='0')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2023, 12, 3, 16, 44, 4, 254175))),
                ('arrive_time', models.DateTimeField(default=datetime.datetime(2023, 12, 3, 16, 44, 4, 254175))),
                ('ride_time', models.DateTimeField(default=datetime.datetime(2023, 12, 3, 16, 44, 4, 254175))),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='order_food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0)),
                ('food_id', models.IntegerField(default=0)),
                ('cnt', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'order_foods',
            },
        ),
    ]
